[package]
name = "doxxer"
authors = ["Karlis Vagalis <karlis.vagalis@gmail.com>"]
version = "0.0.0"
edition = "2021"
license = "LGPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
git2 = "0.20.2"
semver = "1.0.26"
